require('dotenv').config();
const express = require('express');
const session = require('express-session');
const bcrypt = require('bcryptjs');
const path = require('path');
const db = require('./db');
const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(session({ secret: process.env.SESSION_SECRET || 'development-only-change-me', resave: false, saveUninitialized: false, cookie: { httpOnly: true, sameSite: 'lax', maxAge: 8 * 60 * 60 * 1000 } }));
app.use(express.static(path.join(__dirname, 'public')));
const asyncRoute = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
const fail = (res, code, message) => res.status(code).json({ error: message });
// The supplied schema uses integer primary keys without AUTO_INCREMENT, so generate the next ID explicitly.
async function nextId(table, column, executor = db) {
  const [rows] = await executor.execute(`SELECT COALESCE(MAX(${column}), 0) + 1 AS nextId FROM ${table}`);
  return rows[0].nextId;
}
const studentOnly = (req, res, next) => req.session.user?.role === 'student' ? next() : fail(res, 401, 'Please sign in as a student.');
const adminOnly = (req, res, next) => req.session.user?.role === 'admin' ? next() : fail(res, 401, 'Please sign in as an administrator.');
const auth = (req, res, next) => req.session.user ? next() : fail(res, 401, 'Please sign in.');
async function passwordMatches(input, stored) {
  if (!stored) return false;
  return /^\$2[aby]\$/.test(String(stored)) ? bcrypt.compare(input, stored) : input === String(stored);
}
app.get('/api/me', (req, res) => res.json({ user: req.session.user || null }));
app.post('/api/student/login', asyncRoute(async (req, res) => {
  const { Student_ID, password } = req.body;
  if (!Student_ID || !password) return fail(res, 400, 'Enter your student ID and password.');
  const [rows] = await db.execute('SELECT Student_ID, Name, Email, Branch, `Year`, Phone, Password FROM Student WHERE Student_ID = ?', [Student_ID]);
  if (!rows.length || !await passwordMatches(password, rows[0].Password)) return fail(res, 401, 'Invalid student ID or password.');
  const { Password, ...user } = rows[0]; req.session.user = { ...user, role: 'student' }; res.json({ user: req.session.user });
}));
app.post('/api/admin/login', asyncRoute(async (req, res) => {
  const { email, password } = req.body;
  if (!email || !password) return fail(res, 400, 'Enter your email and password.');
  const [rows] = await db.execute('SELECT Admin_ID, Name, Email, Password FROM Admin WHERE Email = ?', [email]);
  if (!rows.length || !await passwordMatches(password, rows[0].Password)) return fail(res, 401, 'Invalid administrator email or password.');
  const { Password, ...user } = rows[0]; req.session.user = { ...user, role: 'admin' }; res.json({ user: req.session.user });
}));
app.post('/api/logout', (req, res) => req.session.destroy(() => res.json({ ok: true })));
app.get('/api/elections', asyncRoute(async (req, res) => { const [r] = await db.execute('SELECT Election_ID, Election_Name, Start_Date, End_Date, Status FROM Election ORDER BY Start_Date DESC'); res.json(r); }));
app.get('/api/elections/:id', asyncRoute(async (req, res) => { const [r] = await db.execute('SELECT Election_ID, Election_Name, Start_Date, End_Date, Status FROM Election WHERE Election_ID = ?', [req.params.id]); if (!r.length) return fail(res,404,'Election not found.'); const [positions] = await db.execute('SELECT DISTINCT ep.Position_ID, ep.Position_Name, ep.Max_Winners FROM Election_Position ep JOIN Candidate c ON c.Position_ID=ep.Position_ID WHERE c.Election_ID=? ORDER BY ep.Position_ID', [req.params.id]); res.json({ ...r[0], positions }); }));
app.get('/api/elections/:id/candidates', asyncRoute(async (req, res) => { const [r] = await db.execute('SELECT c.Candidate_ID, c.Election_ID, c.Position_ID, c.Manifesto, s.Name, s.Branch, s.`Year`, ep.Position_Name FROM Candidate c JOIN Student s ON s.Student_ID=c.Student_ID JOIN Election e ON e.Election_ID=c.Election_ID JOIN Election_Position ep ON ep.Position_ID=c.Position_ID WHERE c.Election_ID=? ORDER BY ep.Position_ID,s.Name', [req.params.id]); res.json(r); }));
app.get('/api/students/:id', studentOnly, asyncRoute(async (req,res)=>{ if(String(req.session.user.Student_ID)!==String(req.params.id)) return fail(res,403,'You can only view your own profile.'); const [r]=await db.execute('SELECT Student_ID,Name,Email,Branch,`Year`,Phone FROM Student WHERE Student_ID=?',[req.params.id]); res.json(r[0]||{}); }));
app.get('/api/verification-status/:electionId',studentOnly,asyncRoute(async(req,res)=>{const [r]=await db.execute('SELECT Verification_Status FROM Voter_Verification WHERE Student_ID=? AND Election_ID=?',[req.session.user.Student_ID,req.params.electionId]);res.json({verified:!!r.length&&String(r[0].Verification_Status).toLowerCase()==='verified'});}));
app.put('/api/student/profile', studentOnly, asyncRoute(async(req,res)=>{const {Email,Branch,Year,Phone}=req.body; if(!Email||!Branch||!Year) return fail(res,400,'Email, branch and year are required.'); await db.execute('UPDATE Student SET Email=?,Branch=?,`Year`=?,Phone=? WHERE Student_ID=?',[Email,Branch,Year,Phone||null,req.session.user.Student_ID]); Object.assign(req.session.user,{Email,Branch,Year,Phone});res.json({user:req.session.user});}));
app.get('/api/results/:electionId', asyncRoute(async(req,res)=>{const [e]=await db.execute('SELECT Status,End_Date FROM Election WHERE Election_ID=?',[req.params.electionId]);if(!e.length)return fail(res,404,'Election not found.');if(String(e[0].Status).toLowerCase()==='active'&&new Date(e[0].End_Date)>=new Date())return fail(res,403,'Results will be available after the election ends.'); const [r]=await db.execute('SELECT c.Candidate_ID,s.Name AS Candidate_Name,ep.Position_Name,COALESCE(er.Vote_Count,counts.Vote_Count,0) AS Vote_Count FROM Candidate c JOIN Student s ON s.Student_ID=c.Student_ID JOIN Election_Position ep ON ep.Position_ID=c.Position_ID LEFT JOIN Election_Result er ON er.Election_ID=c.Election_ID AND er.Position_ID=c.Position_ID AND er.Candidate_ID=c.Candidate_ID LEFT JOIN (SELECT Candidate_ID,Election_ID,COUNT(*) AS Vote_Count FROM Vote WHERE Election_ID=? GROUP BY Candidate_ID,Election_ID) counts ON counts.Candidate_ID=c.Candidate_ID AND counts.Election_ID=c.Election_ID WHERE c.Election_ID=? ORDER BY ep.Position_ID,Vote_Count DESC,s.Name',[req.params.electionId,req.params.electionId]);res.json(r);}));
app.post('/api/votes',studentOnly,asyncRoute(async(req,res)=>{const {Election_ID,Candidate_ID}=req.body, sid=req.session.user.Student_ID;if(!Election_ID||!Candidate_ID)return fail(res,400,'Choose a candidate before confirming your vote.');const [e]=await db.execute('SELECT Status,Start_Date,End_Date FROM Election WHERE Election_ID=?',[Election_ID]);if(!e.length)return fail(res,404,'Election not found.');if(String(e[0].Status).toLowerCase()!=='active'||new Date(e[0].Start_Date)>new Date()||new Date(e[0].End_Date)<new Date())return fail(res,400,'This election is not active.');const [v]=await db.execute("SELECT Verification_Status FROM Voter_Verification WHERE Student_ID=? AND Election_ID=?",[sid,Election_ID]);if(!v.length||String(v[0].Verification_Status).toLowerCase()!=='verified')return fail(res,403,'You are not verified for this election.');const [c]=await db.execute('SELECT Candidate_ID FROM Candidate WHERE Candidate_ID=? AND Election_ID=?',[Candidate_ID,Election_ID]);if(!c.length)return fail(res,404,'Candidate not found for this election.');try{const voteId=await nextId('Vote','Vote_ID');await db.execute('INSERT INTO Vote (Vote_ID,Student_ID,Candidate_ID,Election_ID,Vote_Time) VALUES (?,?,?,?,NOW())',[voteId,sid,Candidate_ID,Election_ID]);}catch(err){if(err.code==='ER_DUP_ENTRY')return fail(res,409,'You have already voted in this election.');throw err;}res.status(201).json({message:'Your vote has been recorded successfully.'});}));
app.get('/api/complaints/student/:studentId',studentOnly,asyncRoute(async(req,res)=>{if(String(req.session.user.Student_ID)!==String(req.params.studentId))return fail(res,403,'Access denied.');const [r]=await db.execute('SELECT c.Complaint_ID,c.Election_ID,e.Election_Name,c.Description,c.Status,c.Created_At FROM Complaint c JOIN Election e ON e.Election_ID=c.Election_ID WHERE c.Student_ID=? ORDER BY c.Created_At DESC',[req.params.studentId]);res.json(r);}));
app.post('/api/complaints',studentOnly,asyncRoute(async(req,res)=>{const {Election_ID,Description}=req.body;if(!Election_ID||!Description?.trim())return fail(res,400,'Select an election and enter a description.');const [e]=await db.execute('SELECT Election_ID FROM Election WHERE Election_ID=?',[Election_ID]);if(!e.length)return fail(res,404,'Election not found.');const id=await nextId('Complaint','Complaint_ID');await db.execute("INSERT INTO Complaint (Complaint_ID,Student_ID,Election_ID,Description,Status,Created_At) VALUES (?,?,?,?,'Pending',NOW())",[id,req.session.user.Student_ID,Election_ID,Description.trim()]);res.status(201).json({message:'Complaint submitted.'});}));
// Admin summary and CRUD. Every table/column identifier here follows the supplied schema.
app.get('/api/admin/summary',adminOnly,asyncRoute(async(req,res)=>{const [[s]] = await db.execute('SELECT COUNT(*) n FROM Student');const [[e]] = await db.execute("SELECT COUNT(*) n FROM Election WHERE LOWER(Status)='active'");const [[c]] = await db.execute('SELECT COUNT(*) n FROM Candidate');const [[v]] = await db.execute('SELECT COUNT(*) n FROM Vote');const [[p]] = await db.execute("SELECT COUNT(*) n FROM Complaint WHERE LOWER(Status)='pending'");res.json({students:s.n,elections:e.n,candidates:c.n,votes:v.n,complaints:p.n});}));
app.get('/api/admin/students',adminOnly,asyncRoute(async(req,res)=>{const [r]=await db.execute('SELECT Student_ID,Name,Email,Branch,`Year`,Phone FROM Student ORDER BY Name');res.json(r);}));
app.post('/api/admin/students',adminOnly,asyncRoute(async(req,res)=>{const {Student_ID,Name,Email,Branch,Year,Phone,Password}=req.body;if(!Student_ID||!Name||!Email||!Branch||!Year||!Password)return fail(res,400,'Complete all required student fields.');await db.execute('INSERT INTO Student (Student_ID,Name,Email,Branch,`Year`,Phone,Password) VALUES (?,?,?,?,?,?,?)',[Student_ID,Name,Email,Branch,Year,Phone||null,await bcrypt.hash(Password,10)]);res.status(201).json({message:'Student created.'});}));
app.put('/api/admin/students/:id',adminOnly,asyncRoute(async(req,res)=>{const {Name,Email,Branch,Year,Phone,Password}=req.body;if(!Name||!Email||!Branch||!Year)return fail(res,400,'Complete required fields.');if(Password)await db.execute('UPDATE Student SET Name=?,Email=?,Branch=?,`Year`=?,Phone=?,Password=? WHERE Student_ID=?',[Name,Email,Branch,Year,Phone||null,await bcrypt.hash(Password,10),req.params.id]);else await db.execute('UPDATE Student SET Name=?,Email=?,Branch=?,`Year`=?,Phone=? WHERE Student_ID=?',[Name,Email,Branch,Year,Phone||null,req.params.id]);res.json({message:'Student updated.'});}));
app.delete('/api/admin/students/:id',adminOnly,asyncRoute(async(req,res)=>{await db.execute('DELETE FROM Student WHERE Student_ID=?',[req.params.id]);res.json({message:'Student deleted.'});}));
app.get('/api/admin/elections',adminOnly,asyncRoute(async(req,res)=>{const [r]=await db.execute('SELECT * FROM Election ORDER BY Start_Date DESC');res.json(r);}));
app.post('/api/admin/elections',adminOnly,asyncRoute(async(req,res)=>{const {Election_Name,Start_Date,End_Date,Status}=req.body;if(!Election_Name||!Start_Date||!End_Date||new Date(Start_Date)>new Date(End_Date))return fail(res,400,'Enter valid election details and dates.');const id=await nextId('Election','Election_ID');await db.execute('INSERT INTO Election (Election_ID,Election_Name,Start_Date,End_Date,Status) VALUES (?,?,?,?,?)',[id,Election_Name,Start_Date,End_Date,Status||'Upcoming']);res.status(201).json({message:'Election created.'});}));
app.put('/api/admin/elections/:id',adminOnly,asyncRoute(async(req,res)=>{const {Election_Name,Start_Date,End_Date,Status}=req.body;if(!Election_Name||!Start_Date||!End_Date||new Date(Start_Date)>new Date(End_Date))return fail(res,400,'Enter valid election details and dates.');await db.execute('UPDATE Election SET Election_Name=?,Start_Date=?,End_Date=?,Status=? WHERE Election_ID=?',[Election_Name,Start_Date,End_Date,Status,req.params.id]);res.json({message:'Election updated.'});}));
app.delete('/api/admin/elections/:id',adminOnly,asyncRoute(async(req,res)=>{await db.execute('DELETE FROM Election WHERE Election_ID=?',[req.params.id]);res.json({message:'Election deleted.'});}));
app.get('/api/admin/positions',adminOnly,asyncRoute(async(req,res)=>{const [r]=await db.execute('SELECT Position_ID,Position_Name,Max_Winners FROM Election_Position');res.json(r);}));
app.post('/api/admin/positions',adminOnly,asyncRoute(async(req,res)=>{const {Position_Name,Max_Winners}=req.body;if(!Position_Name||!Number.isInteger(Number(Max_Winners))||Number(Max_Winners)<1)return fail(res,400,'Enter a position name and positive winner count.');const id=await nextId('Election_Position','Position_ID');await db.execute('INSERT INTO Election_Position (Position_ID,Position_Name,Max_Winners) VALUES (?,?,?)',[id,Position_Name,Max_Winners]);res.status(201).json({message:'Position created.'});}));
app.put('/api/admin/positions/:id',adminOnly,asyncRoute(async(req,res)=>{const {Position_Name,Max_Winners}=req.body;if(!Position_Name||Number(Max_Winners)<1)return fail(res,400,'Enter valid position details.');await db.execute('UPDATE Election_Position SET Position_Name=?,Max_Winners=? WHERE Position_ID=?',[Position_Name,Max_Winners,req.params.id]);res.json({message:'Position updated.'});}));
app.delete('/api/admin/positions/:id',adminOnly,asyncRoute(async(req,res)=>{await db.execute('DELETE FROM Election_Position WHERE Position_ID=?',[req.params.id]);res.json({message:'Position deleted.'});}));
app.get('/api/admin/candidates',adminOnly,asyncRoute(async(req,res)=>{const [r]=await db.execute('SELECT c.Candidate_ID,c.Student_ID,c.Election_ID,c.Position_ID,c.Manifesto,s.Name,s.Branch,s.`Year`,e.Election_Name,ep.Position_Name FROM Candidate c JOIN Student s ON s.Student_ID=c.Student_ID JOIN Election e ON e.Election_ID=c.Election_ID JOIN Election_Position ep ON ep.Position_ID=c.Position_ID ORDER BY e.Election_ID');res.json(r);}));
app.post('/api/admin/candidates',adminOnly,asyncRoute(async(req,res)=>{const {Student_ID,Election_ID,Position_ID,Manifesto}=req.body;if(!Student_ID||!Election_ID||!Position_ID)return fail(res,400,'Select a student, election and position.');const id=await nextId('Candidate','Candidate_ID');await db.execute('INSERT INTO Candidate (Candidate_ID,Student_ID,Election_ID,Position_ID,Manifesto) VALUES (?,?,?,?,?)',[id,Student_ID,Election_ID,Position_ID,Manifesto||'']);res.status(201).json({message:'Candidate added.'});}));
app.put('/api/admin/candidates/:id',adminOnly,asyncRoute(async(req,res)=>{const {Student_ID,Election_ID,Position_ID,Manifesto}=req.body;await db.execute('UPDATE Candidate SET Student_ID=?,Election_ID=?,Position_ID=?,Manifesto=? WHERE Candidate_ID=?',[Student_ID,Election_ID,Position_ID,Manifesto||'',req.params.id]);res.json({message:'Candidate updated.'});}));
app.delete('/api/admin/candidates/:id',adminOnly,asyncRoute(async(req,res)=>{await db.execute('DELETE FROM Candidate WHERE Candidate_ID=?',[req.params.id]);res.json({message:'Candidate deleted.'});}));
app.get('/api/admin/verification',adminOnly,asyncRoute(async(req,res)=>{const [r]=await db.execute('SELECT v.Verification_ID,v.Student_ID,v.Election_ID,v.Verification_Status,v.Verified_At,s.Name,e.Election_Name FROM Voter_Verification v JOIN Student s ON s.Student_ID=v.Student_ID JOIN Election e ON e.Election_ID=v.Election_ID ORDER BY e.Election_ID,s.Name');res.json(r);}));
app.put('/api/admin/verification/:id',adminOnly,asyncRoute(async(req,res)=>{const status=req.body.Verification_Status;if(!['Verified','Unverified'].includes(status))return fail(res,400,'Status must be Verified or Unverified.');await db.execute('UPDATE Voter_Verification SET Verification_Status=?,Verified_At=IF(?=\'Verified\',NOW(),NULL) WHERE Verification_ID=?',[status,status,req.params.id]);res.json({message:'Verification updated.'});}));
app.post('/api/admin/verification',adminOnly,asyncRoute(async(req,res)=>{const {Student_ID,Election_ID,Verification_Status}=req.body;const status=Verification_Status==='Verified'?'Verified':'Unverified';const id=await nextId('Voter_Verification','Verification_ID');await db.execute('INSERT INTO Voter_Verification (Verification_ID,Student_ID,Election_ID,Verification_Status,Verified_At) VALUES (?,?,?,?,IF(?=\'Verified\',NOW(),NULL)) ON DUPLICATE KEY UPDATE Verification_Status=VALUES(Verification_Status),Verified_At=VALUES(Verified_At)',[id,Student_ID,Election_ID,status,status]);res.status(201).json({message:'Voter verification saved.'});}));
app.get('/api/admin/votes',adminOnly,asyncRoute(async(req,res)=>{const [r]=await db.execute('SELECT v.Vote_ID,v.Student_ID,s.Name AS Student_Name,v.Candidate_ID,cs.Name AS Candidate_Name,v.Election_ID,e.Election_Name,v.Vote_Time FROM Vote v JOIN Student s ON s.Student_ID=v.Student_ID JOIN Candidate c ON c.Candidate_ID=v.Candidate_ID JOIN Student cs ON cs.Student_ID=c.Student_ID JOIN Election e ON e.Election_ID=v.Election_ID ORDER BY v.Vote_Time DESC');res.json(r);}));
app.post('/api/admin/results/:electionId/generate',adminOnly,asyncRoute(async(req,res)=>{const id=req.params.electionId;const [e]=await db.execute('SELECT Election_ID,Status,End_Date FROM Election WHERE Election_ID=?',[id]);if(!e.length)return fail(res,404,'Election not found.');if(String(e[0].Status).toLowerCase()==='active'&&new Date(e[0].End_Date)>=new Date())return fail(res,400,'End the election before generating results.');const conn=await db.getConnection();try{await conn.beginTransaction();const [counts]=await conn.execute('SELECT c.Candidate_ID,c.Position_ID,COUNT(v.Vote_ID) AS Vote_Count FROM Candidate c LEFT JOIN Vote v ON v.Candidate_ID=c.Candidate_ID AND v.Election_ID=c.Election_ID WHERE c.Election_ID=? GROUP BY c.Candidate_ID,c.Position_ID',[id]);for(const x of counts){const [existing]=await conn.execute('SELECT Result_ID FROM Election_Result WHERE Election_ID=? AND Position_ID=? AND Candidate_ID=? LIMIT 1',[id,x.Position_ID,x.Candidate_ID]);if(existing.length)await conn.execute('UPDATE Election_Result SET Vote_Count=? WHERE Result_ID=?',[x.Vote_Count,existing[0].Result_ID]);else{const resultId=await nextId('Election_Result','Result_ID',conn);await conn.execute('INSERT INTO Election_Result (Result_ID,Election_ID,Position_ID,Candidate_ID,Vote_Count) VALUES (?,?,?,?,?)',[resultId,id,x.Position_ID,x.Candidate_ID,x.Vote_Count]);}}await conn.commit();res.json({message:'Results generated.',results:counts});}catch(err){await conn.rollback();throw err;}finally{conn.release();}}));
app.get('/api/admin/complaints',adminOnly,asyncRoute(async(req,res)=>{const [r]=await db.execute('SELECT c.Complaint_ID,c.Student_ID,s.Name AS Student_Name,c.Election_ID,e.Election_Name,c.Description,c.Status,c.Created_At FROM Complaint c JOIN Student s ON s.Student_ID=c.Student_ID JOIN Election e ON e.Election_ID=c.Election_ID ORDER BY c.Created_At DESC');res.json(r);}));
app.put('/api/admin/complaints/:id',adminOnly,asyncRoute(async(req,res)=>{const status=req.body.Status;if(!['Pending','Resolved'].includes(status))return fail(res,400,'Status must be Pending or Resolved.');await db.execute('UPDATE Complaint SET Status=? WHERE Complaint_ID=?',[status,req.params.id]);res.json({message:'Complaint status updated.'});}));
app.use('/api', (err,req,res,next)=>{console.error(err);if(err.code==='ER_DUP_ENTRY')return fail(res,409,'A record with these details already exists.');if(err.code==='ER_NO_REFERENCED_ROW_2')return fail(res,400,'Select valid related records.');if(err.code==='ER_ROW_IS_REFERENCED_2')return fail(res,409,'This record is in use and cannot be deleted.');res.status(500).json({error:'A database error occurred. Check the server configuration and try again.'});});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
const port=process.env.PORT||5000;
app.listen(port,()=>console.log(`Voting portal running at http://localhost:${port}`));
